language: node_js
node_js: ["4"]
  
install:
  - npm install

script:
  - npm run test

deploy:
  provider: script
  script:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish
  on:
    tags: true
